#!/bin/sh
export TMPDIR=/mnt/HD/HD_a2/Nas_Prog/mc/mc/tmp
if [ ! -e $TMPDIR ]; then
  mkdir $TMPDIR
fi

if [ ! -e /system ]; then
  mkdir /system
fi

if [ ! -e /system/etc ]; then
  ln -s /mnt/HD/HD_a2/Nas_Prog/mc/mc/system/etc /system/etc
fi

if [ ! -e /system/libexec ]; then
  ln -s /mnt/HD/HD_a2/Nas_Prog/mc/mc/system/libexec /system/libexec
fi

if [ ! -e /system/share ]; then
  ln -s /mnt/HD/HD_a2/Nas_Prog/mc/mc/system/share /system/share
fi

if [ ! -e /system/xbin ]; then
  ln -s /mnt/HD/HD_a2/Nas_Prog/mc/mc/system/xbin /system/xbin
fi

if [ ! -e /bin/mc ]; then
  ln -s /mnt/HD/HD_a2/Nas_Prog/mc/mc /bin/mc
fi

export TERM=xterm
export TERMINFO=/system/etc/terminfo
/system/xbin/mc.real $*
